export const ROUTES = {
    ChatMessenger: 'ChatMessengerScreen',
    Login: 'LoginScreen',
    ForgetPassword: 'ForgetPasswordScreen',
    Register: 'RegisterScreen',
    Main: 'MainScreen',
    NewPost: 'NewPostScreen',
    AddFriend: 'AddFriendScreen',
    Comment: 'CommentScreen',
    Search: 'SearchScreen',
    Setting: 'SettingScreen',
    MediaPicker: 'MediaPicker',
    ChatInformation: 'ChatInformation',
    EditPost: 'EditPostScreen',
    MainMessenger: 'MainMessengerScreen',
    Demo: 'DemoScreen',
    SharePost: 'SharePostScreen',
    Hello: 'HelloScreen',
};
